force-app/main/default/objects/Stellar_DEX_Offer__c/Stellar_DEX_Offer__c.object-meta.xml
<CustomObject>
    <description>Stores stellar dex offer information such as ID, buying and selling assets, amount and price.</description>
    <label>Stellar DEX Offer</label>
    <nameField>
        <label>Stellar DEX Offer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stellar DEX Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stellar_DEX_Offer__c/fields/Buying_Asset__c.field-meta.xml
<CustomField>
    <fullName>Buying_Asset__c</fullName>
    <label>Buying Asset</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stellar_DEX_Offer__c/fields/Offer_Amount__c.field-meta.xml
<CustomField>
    <fullName>Offer_Amount__c</fullName>
    <label>Offer Amount</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stellar_DEX_Offer__c/fields/Offer_ID__c.field-meta.xml
<CustomField>
    <fullName>Offer_ID__c</fullName>
    <externalId>true</externalId>
    <label>Offer ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stellar_DEX_Offer__c/fields/Offer_Price__c.field-meta.xml
<CustomField>
    <fullName>Offer_Price__c</fullName>
    <label>Offer Price</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stellar_DEX_Offer__c/fields/Selling_Asset__c.field-meta.xml
<CustomField>
    <fullName>Selling_Asset__c</fullName>
    <label>Selling Asset</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stellar_DEX_Offer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Open&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Partially Filled</fullName>
            </value>
            <value>
                <fullName>Filled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stellar_DEX_Offer__c/fields/Stellar_Offer_Trade_Notification__c.field-meta.xml
<CustomField>
    <fullName>Stellar_Offer_Trade_Notification__c</fullName>
    <label>Stellar Offer Trade Notification</label>
    <referenceTo>Stellar_Offer_Trade_Notification__c</referenceTo>
    <relationshipLabel>Stellar DEX Offers</relationshipLabel>
    <relationshipName>Stellar_DEX_Offers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stellar_Offer_Trade_Notification__c/Stellar_Offer_Trade_Notification__c.object-meta.xml
<CustomObject>
    <description>Master object that store public wallet address and have child Offer objects related.</description>
    <label>Stellar Offer Trade Notification</label>
    <nameField>
        <displayFormat>SOTN-{00000}</displayFormat>
        <label>Stellar Offer Trade Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stellar Offer Trade Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stellar_Offer_Trade_Notification__c/fields/Wallet_Address__c.field-meta.xml
<CustomField>
    <fullName>Wallet_Address__c</fullName>
    <label>Wallet Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StroopForceTradeNotitifcationScheduler.cls
public with sharing class StroopForceTradeNotitifcationScheduler implements Schedulable{
    
    
    public String walletAddress;
    

    public StroopForceTradeNotitifcationScheduler(String walletAddr){
        walletAddress = walletAddr;

    }

    public void execute(SchedulableContext sc) {

        String query = 'SELECT Id,Buying_Asset__c,Selling_Asset__c,Offer_Amount__c,Name,Offer_ID__c,Offer_Price__c,Stellar_Offer_Trade_Notification__c,Stellar_Offer_Trade_Notification__r.Email_Address__c FROM Stellar_DEX_Offer__c'
                    + ' WHERE Stellar_Offer_Trade_Notification__r.Wallet_Address__c = ' + '\'' + walletAddress + '\'' + ' AND  Stellar_Offer_Trade_Notification__r.Active__c = TRUE AND Status__c <> ' + '\'' + 'Filled' + '\'';
      
        

        StroopForceOfferFillFetch_Batch bat = new StroopForceOfferFillFetch_Batch(query, walletAddress);

        String jobId = Database.executeBatch(bat);

        Datetime currDT = Datetime.now();
        Integer min = currDT.addMinutes(5).minute();
        String newCronExp = '0 ' + min + ' * * * ?';

        System.abortJob(sc.getTriggerId());

        StroopForceTradeNotitifcationScheduler ts = new StroopForceTradeNotitifcationScheduler(walletAddress);

        System.schedule(walletAddress + ' DEX Trade Notify', newCronExp, ts);
    }
}