force-app/main/default/objects/Stellar_DEX_Offer__c/Stellar_DEX_Offer__c.object-meta.xml
<CustomObject>
    <description>Stores stellar dex offer information such as ID, buying and selling assets, amount and price.</description>
    <label>Stellar DEX Offer</label>
    <nameField>
        <label>Stellar DEX Offer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stellar DEX Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stellar_DEX_Offer__c/fields/Buying_Asset__c.field-meta.xml
<CustomField>
    <fullName>Buying_Asset__c</fullName>
    <label>Buying Asset</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stellar_DEX_Offer__c/fields/Offer_Amount__c.field-meta.xml
<CustomField>
    <fullName>Offer_Amount__c</fullName>
    <label>Offer Amount</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stellar_DEX_Offer__c/fields/Offer_ID__c.field-meta.xml
<CustomField>
    <fullName>Offer_ID__c</fullName>
    <externalId>true</externalId>
    <label>Offer ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stellar_DEX_Offer__c/fields/Offer_Price__c.field-meta.xml
<CustomField>
    <fullName>Offer_Price__c</fullName>
    <label>Offer Price</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stellar_DEX_Offer__c/fields/Percentage_Away_from_Spread_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Percentage_Away_from_Spread_Threshold__c</fullName>
    <label>Percentage Away from Spread Threshold</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Stellar_DEX_Offer__c/fields/Selling_Asset__c.field-meta.xml
<CustomField>
    <fullName>Selling_Asset__c</fullName>
    <label>Selling Asset</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stellar_DEX_Offer__c/fields/Stellar_Offer_Trade_Notification__c.field-meta.xml
<CustomField>
    <fullName>Stellar_Offer_Trade_Notification__c</fullName>
    <label>Stellar Offer Trade Notification</label>
    <referenceTo>Stellar_Offer_Trade_Notification__c</referenceTo>
    <relationshipLabel>Stellar DEX Offers</relationshipLabel>
    <relationshipName>Stellar_DEX_Offers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stellar_Offer_Trade_Notification__c/Stellar_Offer_Trade_Notification__c.object-meta.xml
<CustomObject>
    <description>Master object that store public wallet address and have child Offer objects related.</description>
    <label>Stellar Offer Trade Notification</label>
    <nameField>
        <displayFormat>SOTN-{00000}</displayFormat>
        <label>Stellar Offer Trade Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stellar Offer Trade Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stellar_Offer_Trade_Notification__c/fields/Stellar_Wallet_Address__c.field-meta.xml
<CustomField>
    <fullName>Stellar_Wallet_Address__c</fullName>
    <label>Stellar Wallet Address</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Stellar_Offer_Trade_Notification__c/fields/Wallet_Address__c.field-meta.xml
<CustomField>
    <fullName>Wallet_Address__c</fullName>
    <label>Wallet Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StroopForceTradeSettingService.cls
public with sharing class StroopForceTradeSettingService {
    




    @AuraEnabled
    public static String saveSetting(String walletAddr, String emailAddr, Boolean active){
        
        String result = 'success';

        try {

            

            List<Stellar_Offer_Trade_Notification__c> setting = [SELECT Id, Active__c, Stellar_Wallet_Address__c, Email_Address__c FROM Stellar_Offer_Trade_Notification__c
                    WHERE Wallet_Address__c = :walletAddr limit 1];
            
            if(!active && !setting.isEmpty()){
                delete setting;
            }
            else if(active && !setting.isEmpty()){
                setting[0].Stellar_Wallet_Address__c = walletAddr;
                setting[0].Wallet_Address__c = walletAddr;
                setting[0].Active__c = true;
                setting[0].Email_Address__c = emailAddr;

                update setting[0];
            }
            else if(active && setting.isEmpty()){
                Stellar_Offer_Trade_Notification__c newSetting = new Stellar_Offer_Trade_Notification__c(
                    Stellar_Wallet_Address__c = walletAddr,
                    Wallet_Address__c = walletAddr,
                    Active__c = true,
                    Email_Address__c = emailAddr
                ); 
                
                insert newSetting;

            }


            return result;



            
        } catch (Exception e) {
            result = e.getMessage();
            
           // throw new AuraHandledException(e.getMessage());

            return result;
        }
    }

    @AuraEnabled
    public static String saveDEXOffer(String offerId, String ba, String sa, String oa, String op, String walletAddr, String spreadDevPer){
        
        String result = 'success';

        try {

            System.debug('wallet addr: ' + walletAddr);

            List<Stellar_Offer_Trade_Notification__c> tradeSetting = [SELECT Id FROM Stellar_Offer_Trade_Notification__c 
                WHERE Wallet_Address__c = :walletAddr];
            
            System.debug('Trade setting size: ' + tradeSetting.size());

            Decimal spreadDevPerVal = spreadDevPer == null || spreadDevPer == 'null' ? null : Decimal.valueOf(spreadDevPer);

            if(!tradeSetting.isEmpty()){

                Stellar_DEX_Offer__c dexOffer = new Stellar_DEX_Offer__c(
                    Buying_Asset__c = ba,
                    Selling_Asset__c = sa,
                    Offer_Amount__c = Decimal.valueOf(oa),
                    Name = offerId,
                    Offer_ID__c = offerId,
                    Offer_Price__c = Decimal.valueOf(op),
                    Stellar_Offer_Trade_Notification__c = tradeSetting[0].Id,
                    Percentage_Away_from_Spread_Threshold__c = spreadDevPerVal
  
                );

                upsert dexOffer Offer_ID__c;

                return result;

            }
            else{
                result = 'No trade notification setting set-up. Go to settings and toggle the Trade Notification off and on again';
                return result;
            }


                


            
        } catch (Exception e) {
            result = e.getMessage();

            return result;
        }
    }

    @AuraEnabled
    public static String deleteDEXOffer(String offerId){

        String result = 'success';

        try {
            
            List<Stellar_DEX_Offer__c> delOffer = [SELECT Id FROM Stellar_DEX_Offer__c WHERE Offer_ID__c = :offerId];
            delete delOffer;


            return result;

        } catch (Exception e) {
            result = e.getMessage();
            return result;
        }
    }

    @AuraEnabled
    public static String initTradeNotificationScheduler(String walletAddr){

        String result = 'success';
        try {

            StroopForceTradeNotitifcationScheduler ts = new StroopForceTradeNotitifcationScheduler(walletAddr);
            Datetime currDT = Datetime.now();
            Integer min = currDT.addMinutes(5).minute();
            String newCronExp = '0 ' + min + ' * * * ?';
            
            System.schedule(walletAddr + ' DEX Trade Notify', newCronExp, ts);


            return result;
            
        } catch (Exception e) {
            result = e.getMessage();

            return result;
        }
    }

    @AuraEnabled
    public static String deleteTradeNotificationScheduler(String walletAddr){

        String result = 'success';
        try {

            String jobName = walletAddr + ' DEX Trade Notify';
            List<CronTrigger> jobs = [SELECT Id, CronJobDetail.Id, CronJobDetail.Name, CronJobDetail.JobType FROM CronTrigger 
                        WHERE CronJobDetail.Name =: jobName];

            
            for(CronTrigger job : jobs){
                System.abortJob(job.Id);
            }


            return result;
            
        } catch (Exception e) {
            result = e.getMessage();

            return result;
        }
    }



}