force-app/main/default/objects/Stellar_DEX_Offer__c/Stellar_DEX_Offer__c.object-meta.xml
<CustomObject>
    <description>Stores stellar dex offer information such as ID, buying and selling assets, amount and price.</description>
    <label>Stellar DEX Offer</label>
    <nameField>
        <label>Stellar DEX Offer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stellar DEX Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stellar_DEX_Offer__c/fields/Buying_Asset__c.field-meta.xml
<CustomField>
    <fullName>Buying_Asset__c</fullName>
    <label>Buying Asset</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stellar_DEX_Offer__c/fields/Offer_Amount__c.field-meta.xml
<CustomField>
    <fullName>Offer_Amount__c</fullName>
    <label>Offer Amount</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stellar_DEX_Offer__c/fields/Offer_ID__c.field-meta.xml
<CustomField>
    <fullName>Offer_ID__c</fullName>
    <externalId>true</externalId>
    <label>Offer ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stellar_DEX_Offer__c/fields/Offer_Price__c.field-meta.xml
<CustomField>
    <fullName>Offer_Price__c</fullName>
    <label>Offer Price</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stellar_DEX_Offer__c/fields/Selling_Asset__c.field-meta.xml
<CustomField>
    <fullName>Selling_Asset__c</fullName>
    <label>Selling Asset</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stellar_DEX_Offer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Open&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Partially Filled</fullName>
            </value>
            <value>
                <fullName>Filled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stellar_DEX_Offer__c/fields/Stellar_Offer_Trade_Notification__c.field-meta.xml
<CustomField>
    <fullName>Stellar_Offer_Trade_Notification__c</fullName>
    <label>Stellar Offer Trade Notification</label>
    <referenceTo>Stellar_Offer_Trade_Notification__c</referenceTo>
    <relationshipLabel>Stellar DEX Offers</relationshipLabel>
    <relationshipName>Stellar_DEX_Offers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stellar_Offer_Trade_Notification__c/Stellar_Offer_Trade_Notification__c.object-meta.xml
<CustomObject>
    <description>Master object that store public wallet address and have child Offer objects related.</description>
    <label>Stellar Offer Trade Notification</label>
    <nameField>
        <displayFormat>SOTN-{00000}</displayFormat>
        <label>Stellar Offer Trade Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stellar Offer Trade Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/StroopForceOfferFillFetch_Batch.cls
public with sharing class StroopForceOfferFillFetch_Batch implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts{
    
    
    public String query;
    public String walletAddr;
    public List<Stellar_DEX_Offer__c> filledOffers;
    

    public StroopForceOfferFillFetch_Batch(String q, String wa) {

        query = q;
        walletAddr = wa;
        filledOffers = new List<Stellar_DEX_Offer__c>();

    }

    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(query);
     }
  
     public void execute(Database.BatchableContext bc, List<sObject> scope){
        
        String endPt = 'https://horizon.stellar.org/accounts/' + walletAddr + '/offers';
        Http h = new Http();
        HttpRequest req = new HttpRequest();
        HttpResponse resp; 
        List<Stellar_DEX_Offer__c> updDexOffs = new List<Stellar_DEX_Offer__c>();

        req.setMethod('GET');
        req.setEndpoint(endPt);
        req.setHeader('Accept', 'application/json');

        try{
            resp = h.send(req);

            if(resp.getStatusCode() != 200){

            }
            else{
                JSONParser parser = JSON.createParser(resp.getBody());
                Set<String> activeOfferIds = new Set<String>();

                while(parser.nextToken() != null){

                    if (parser.getCurrentToken() == JSONToken.FIELD_NAME && parser.getText() == 'id') {

                        parser.nextToken();
                        activeOfferIds.add(parser.getText());

                    }

                }


                for(Stellar_DEX_Offer__c dexOff : (List<Stellar_DEX_Offer__c>) scope){

                    if(!activeOfferIds.contains(dexOff.Offer_ID__c)){
                        filledOffers.add(dexOff);
                        dexOff.Status__c = 'Filled';
                        updDexOffs.add(dexOff);
                    }

                }

                update updDexOffs;

            }

        }catch(Exception ex){
            System.debug(LoggingLevel.ERROR, ex.getMessage());
        }

     }
  
     public void finish(Database.BatchableContext bc){

        Messaging.SingleEmailMessage sem = new  Messaging.SingleEmailMessage();
        String subj = 'DEX Offers filled for ' + walletAddr; 
        String emBody = '';
        String toAddr;

        for(Stellar_DEX_Offer__c dexOff : filledOffers){

            emBody += 'Offer ID: ' + dexOff.Offer_ID__c + '\n'
                    + 'Sold: ' + dexOff.Selling_Asset__c + '\n'
                    + 'Bought: ' + dexOff.Buying_Asset__c + '\n'
                    + 'Offer Amount: ' + dexOff.Offer_Amount__c + '\n'
                    + 'Offer Price: ' + dexOff.Offer_Price__c + '\n\n';

            toAddr = dexOff.Stellar_Offer_Trade_Notification__r.Email_Address__c;

        }

        sem.subject = subj;
        sem.plainTextBody = emBody;
        sem.toAddresses = new List<String>{toAddr};

        try{
            
            Object retVal = toAddr != null ? Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{sem}) : null;
        }catch(Exception ex){
            System.debug(LoggingLevel.ERROR, ex.getMessage());
        }

     }
}